In [98]:
import numpy as np
from mp_api.client import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from jupyter_jsmol.pymatgen import quick_view

In [99]:
mp_key = "bw9PJDXW6ljZz8DyLmXT49ZnMengQUwm"
mp_id = "mp-30460"

In [100]:
#récupération de la structure
with MPRester(mp_key) as m:
    prim_struc = m.get_structure_by_material_id(mp_id) 
    
#récupération de la structure conventionnelle qui correspond à la maille du fichier CIF symmetrized
conv_struc = SpacegroupAnalyzer(prim_struc).get_conventional_standard_structure()

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

In [101]:
#représentation de la structure conventionnelle
view = quick_view(conv_struc)
display(view)

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [102]:
#récupération des opérations de symétrie
symop = SpacegroupAnalyzer(conv_struc).get_space_group_operations()

#Choix des 3 éléments de symétrie 
i_symop1 = 6
print("Symétrie 1:")
print(symop[i_symop1],"\n")

i_symop2 = 5
print("Symétrie 2:")
print(symop[i_symop2],"\n")

i_symop3 = 24
print("Symétrie 3:")
print(symop[i_symop3],"\n")

#récupération des sites des atomes dans la maille conventionnelle
sites = conv_struc.sites


Symétrie 1:
Rot:
[[-1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.] 

Symétrie 2:
Rot:
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
tau
[0. 0. 0.] 

Symétrie 3:
Rot:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
tau
[0.5 0.5 0. ] 



Premier élément de symétrie

Le premier élément de symétrie fait passer des coordonnées (x,y,z) au coordonnées (-x,y,-z). Il s'agit d'une rotation du deuxième ordre $C_2$ (de 180°) autour de l'axe b. 
La matrice de rotation qui représente cette opération est : $$\left({\begin{array}{cc}
    -1 & 0 & 0 \\
    0 & 1 & 0 \\
    0 & 0 & -1 \\
  \end{array} }\right)$$


Le vecteur représentant la translation est nul.

Cet élément de symétrie est appliqué à l'atome Y dont les coordonnées réduites sont (0,0,0.5)

In [103]:
#atome sur lequel on applique l'élément de symétrie
i_atom1 = 2
at1 = sites[i_atom1]
#opération de symétrie 
op1 = symop[i_symop1]
#coordonnées de la position initiale 
pos_init1 = at1.frac_coords
print("Coordonées réduites de la position avant l'application de l'élément de symétrie:",pos_init1)
#coordonnées de la position finale (après symétrie) 
pos_final1 = op1.operate(pos_init1)
print("Coordonées réduites de la position après application de l'élément de symétrie:",pos_final1)

Coordonées réduites de la position avant l'application de l'élément de symétrie: [0.  0.  0.5]
Coordonées réduites de la position après application de l'élément de symétrie: [ 0.   0.  -0.5]


In [104]:
# représentation 3D de l'opération de symétrie 
view1 = quick_view(conv_struc)
display(view1)
view1.script('draw SYMOP ' + str(i_symop1+1) + ' {atomno = ' + str(4) + '}')

JsmolView(layout=Layout(align_self='stretch', height='400px'))

Deuxième élément de symétrie

Le deuxième élément de symétrie fait passer des coordonnées (x,y,z) au coordonnées (y,x,z). Il s'agit d'un plan mirroir m, le plan $(1 \bar{1} 0)$.

La matrice de rotation qui représente cette opération est : $$\left({\begin{array}{cc}
    0 & 1 & 0 \\
    1 & 0 & 0 \\
    0 & 0 & 1 \\
  \end{array} }\right)$$

Le vecteur représentant la translation est nul : (0,0,0)

Cet élément de symétrie est appliqué à l'atome Ni dont les coordonnées réduites sont (0.75,0.25,0.75)

In [105]:
#atome sur lequel on applique l'élément de symétrie
i_atom2 = 4
at2 = sites[i_atom2]
#opération de symétrie 
op2 = symop[i_symop2]
#coordonnées de la position initiale 
pos_init2 = at2.frac_coords
print("Coordonées réduites de la position avant l'application de l'élément de symétrie:",pos_init2)
#coordonnées de la position finale (après symétrie) 
pos_final2 = op2.operate(pos_init2)
print("Coordonées réduites de la position après application de l'élément de symétrie:",pos_final2)

Coordonées réduites de la position avant l'application de l'élément de symétrie: [0.75 0.25 0.75]
Coordonées réduites de la position après application de l'élément de symétrie: [0.25 0.75 0.75]


In [106]:
# représentation 3D de l'opération de symétrie 
view2 = quick_view(conv_struc)
display(view2)
view2.script('draw SYMOP ' + str(i_symop2 + 1) + ' {atomno = ' + str(i_atom2 + 1) + '}')

JsmolView(layout=Layout(align_self='stretch', height='400px'))

Troisème  élément de symétrie

Le troisième élément de symétrie fait passer des coordonnées (x,y,z) au coordonnées (x+1/2,y+1/2,z). Il s'agit d'une translation pure.

La matrice de rotation qui représente cette opération est la matrice identité car il s'agit d'une translation pure: $$\left({\begin{array}{cc}
    1 & 0 & 0 \\
    0 & 1 & 0 \\
    0 & 0 & 1 \\
  \end{array} }\right)$$

Le vecteur représentant la translation est : (0.5,0.5,0)

Cet élément de symétrie est appliqué à l'atome Bi dont les coordonnées réduites sont (0,0,0)

In [107]:
#atome sur lequel on applique l'élément de symétrie
i_atom3 = 8
at3 = sites[i_atom3]
#opération de symétrie 
op3 = symop[i_symop3]
#coordonnées de la position initiale 
pos_init3 = at3.frac_coords
print("Coordonées réduites de la position avant l'application de l'élément de symétrie:",pos_init3)
#coordonnées de la position finale (après symétrie) 
pos_final3 = op3.operate(pos_init3)
print("Coordonées réduites de la position après application de l'élément de symétrie:",pos_final3)

Coordonées réduites de la position avant l'application de l'élément de symétrie: [0. 0. 0.]
Coordonées réduites de la position après application de l'élément de symétrie: [0.5 0.5 0. ]


In [108]:
# représentation 3D de l'opération de symétrie 
view3 = quick_view(conv_struc)
display(view3)
view3.script('draw SYMOP ' + str(i_symop3 + 1) + ' {atomno = ' + str(i_atom3 + 1) + '}')

JsmolView(layout=Layout(align_self='stretch', height='400px'))